### ISSUE TITLE
setup eslint with oncommit style hook

### ISSUE THREAD

**Issue by OskarDamkjaer** [Dsek-LTH/mataDor#21]

**Comment by wanecek** [comment]
A popular way to do this is to use [husky](https://github.com/typicode/husky). It's quite nice, and I would suggest throwing in automatic formatting with [prettier](https://github.com/prettier/prettier) as well. 

However, it comes with one (considerable?) drawback: It removes the possibility to do partial commits (at least last I checked). Certainly livable, but a bit frustrating. WDYT?

**Comment by OskarDamkjaer** [comment]
Prettier hook used for now, eslint might we interesting in the future though.
