### ISSUE TITLE
Consider using inputmode and pattern instead of input[type="number"]

### ISSUE THREAD

**Issue by wanecek** [Dsek-LTH/mataDor#27]
There's an alternative way to bring up numeric keyboard on mobile devices, which involves a combination of two attributes, one used to cover where browser-support of the other is lacking.

1. `input[inputmode="numeric"]` has [support in Chrome and Android](https://caniuse.com/#feat=input-inputmode)
1. `input[pattern="[0-9]*"]` causes iOS Safari to open the numeric keyboard (must be an exact match with the pattern above). This would also fix #23 

There is a third option as well, which is to use `input[type="tel"]`. It's semantically "wrong", but also "less wrong" than `type="number"` :smile: 

---

If we do decide to stick with the existing `input[type="number"]`, may I suggest setting the `-webkit-apparence` to make it look like an "normal" (text) input? :)

**Comment by OskarDamkjaer** [comment]
Good research! This def sounds like something we should do! :) To bad there is no support for firefox yet, it's my main browser :( I think we still should try the type="tel" and see if it is a better fit

**Comment by wanecek** [comment]
Same. I can try how and see if it works as expected on Firefox and Firefox Focus on Android if you want. On desktop it won't really matter, as you're using a physical keyboard anyway :P And on iOS everything is Safari :)

**Comment by OskarDamkjaer** [comment]
Sounds great! I'm all for it!
