### ISSUE TITLE
Might not want to show notification thing on the big screen? Create a seperate site for users rather than tv?

### ISSUE THREAD

**Issue by OskarDamkjaer** [Dsek-LTH/mataDor#32]

**Comment by OskarDamkjaer** [comment]
sorry bout the wall of text O:)

**Comment by wanecek** [comment]
> I'm thinking we could make the notify panel look nice/unobtrusive and include it on the normal page

This sounds like a fantastic idea! :100: 

> [...] and port the deployed/darkmode/larger font style to a "/tv route" without the notify panel? That route could be aimed esp for screens viewed at a distance and the normal one could be mainly for personal computers/phones.

Sure! Either that, or apply it to the existing route with a query-param. Of course, with React Router, we can just have it render the same component but with a certain prop :) Then, using some basic CSS we should be able to achieve the desired effect :+1:

> Also i think it would be a good idea to consider how many features we want to implement? 

I fully agree. Let's try to keep it as simple as possible. I think the notifications should be an included feature, but the undo button seems a bit unnecessary to me :). Let's try to deploy it asap, and see what features seem to be necessary. We will, for sure, get a lot of feature suggestions, and will have to take on the role of "boring" people to limit the features that are actually implemented. 

> After a point just making sure mataDor is stable [...]

This times a :100: . Let's focus on making it stable and usable :slightly_smiling_face:
