### ISSUE TITLE
Notification crashes on mobile while deployed

### ISSUE THREAD

**Issue by OskarDamkjaer** [Dsek-LTH/mataDor#50]
I redeloyed and mat.10av10.com works but looks a bit wonky on firefox for mobile but not in chrome on mobile. It works locally when "pretending" to be phone but not when a real phone :( Do you know how to debug? @wanecek

**Comment by OskarDamkjaer** [comment]
Debugged it to be that `new Notification` isn't supported via alerts all over the code :l  We could polyfill it if that's the issue?

**Comment by OskarDamkjaer** [comment]
https://caniuse.com/#search=Notification seems to indicate it should work on chrome, though???

**Comment by wanecek** [comment]
Afaiu it should work... You can try remote debugging it, if you can reproduce it on your phone? :) IIRC [this article](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) is pretty good :)

**Comment by OskarDamkjaer** [comment]
Thanks for the tip! I found that chrome on android doesn't like the new Notification constructor!°

**Comment by OskarDamkjaer** [comment]
Chrome seems to need the service worker to do the notifying, added something small from stackover flow to solve it
